const STORAGE_KEYS = {
  SUPABASE_URL: 'ORDER_STOCK_SUPABASE_URL',
  SUPABASE_KEY: 'ORDER_STOCK_SUPABASE_KEY',
  SUPABASE_BUCKET: 'ORDER_STOCK_SUPABASE_BUCKET',
  ACTIVE_TAB: 'ORDER_STOCK_ACTIVE_TAB'
};

const DEFAULT_PRODUCT_BUCKET = 'product-images';

const ORDER_STATUS = {
  PENDING: 'PENDING',
  FACTORY_ORDERED: 'FACTORY_ORDERED',
  DELIVERING: 'DELIVERING',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  RETURNED: 'RETURNED'
};

const ORDER_STATUS_LABELS = {
  PENDING: 'Dang xu ly',
  FACTORY_ORDERED: 'Da order nha may',
  DELIVERING: 'Dang giao hang',
  CANCELLED: 'Da huy order',
  COMPLETED: 'Giao hang thanh cong',
  RETURNED: 'Giao hang khong thanh cong'
};

const FACTORY_STATUS = {
  NEED_ORDER: 'NEED_ORDER',
  ORDERED: 'ORDERED',
  RECEIVED: 'RECEIVED'
};

const FACTORY_STATUS_LABELS = {
  NEED_ORDER: 'Can dat nha may',
  ORDERED: 'Da dat nha may',
  RECEIVED: 'Da nhan hang'
};

const TERMINAL_ORDER_STATUS = [
  ORDER_STATUS.CANCELLED,
  ORDER_STATUS.COMPLETED,
  ORDER_STATUS.RETURNED
];
